go:
    version: 1.14
    cgo: true
repository:
    path: github.com/ubccr/nvidia_gpu_prometheus_exporter
build:
    static: false
    binaries:
        - name: nvidia_gpu_prometheus_exporter
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
